<template>
  <div>{{ t('Swagger automatically generated by data.gouv.fr. This swagger allows you to query data by API by filtering it by column value.') }}</div>
  <div id="swagger-ui"></div>
</template>

<script setup lang="ts">
import { onMounted } from "vue";
import { useI18n } from "vue-i18n";
import { type Resource } from '../../types/resources';
import { config } from "../../config";
import SwaggerUIBundle from 'swagger-ui-dist/swagger-ui-bundle.js';
import 'swagger-ui-dist/swagger-ui.css';

const { t } = useI18n();

const props = defineProps<{
    resource: Resource;
}>();

onMounted(async () => {
  let swaggerUrl = `${config.tabular_api_url}/api/resources/${props.resource.id}/swagger/`
  SwaggerUIBundle({
    dom_id: '#swagger-ui',
    url: swaggerUrl,
  });
});

</script>

